version: "3.9"


services:
  mysqldb:
    container_name: database
    platform: linux/arm64
    image: "mysql:8.0"
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    networks:
      - space-probe-api-network
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: api
    platform: linux/arm64
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - space-probe-api-network
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb",
        "server.port" : "$SPRING_LOCAL_PORT",
        "server.servlet.context-path" : "/api",
        "management.endpoints.web.exposure.include" : "*",
        "management.endpoint.health.show-details" : "always"
      }'
    volumes:
      - ./db/mysql:/data/db
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  space-probe-api-network:
    driver: bridge
